--- 
:log_file: log/mongrel.log
:config_script: 
:pid_file: log/mongrel.pid
:num_processors: 1024
:docroot: public
:config_file: 
:timeout: 0
:host: 0.0.0.0
:group: 
:mime_map: 
:user: 
:environment: production
:port: "3000"
:daemon: false
:prefix: 
:cwd: /usr/local/ulikes
:includes: 
- mongrel
:debug: false
