# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "carriers", :force => true do |t|
    t.column "name",         :string,   :limit => 48
    t.column "email_domain", :string,   :limit => 48
    t.column "created_on",   :datetime
    t.column "updated_on",   :datetime
  end

  create_table "cities", :force => true do |t|
    t.column "name",     :string,  :limit => 50
    t.column "state_id", :integer
  end

  create_table "commands", :force => true do |t|
    t.column "value", :string, :limit => 16
  end

  add_index "commands", ["value"], :name => "commands_value_index", :unique => true

  create_table "conversation_states", :force => true do |t|
    t.column "name", :string, :limit => 32
  end

  create_table "conversations", :force => true do |t|
    t.column "conversation_state_id", :integer
    t.column "user_id",               :integer
    t.column "created_on",            :datetime
    t.column "updated_on",            :datetime
    t.column "next_step_id",          :integer
  end

  create_table "items", :force => true do |t|
    t.column "name",           :string
    t.column "description",    :string,   :limit => 1024
    t.column "keyword_id",     :integer
    t.column "type",           :string,   :limit => 50
    t.column "active",         :boolean,                  :default => true
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
    t.column "segment_id",     :integer
    t.column "street",         :string
    t.column "city_id",        :integer
    t.column "state_id",       :integer
    t.column "zip_code_id",    :integer
    t.column "latitude",       :float
    t.column "longitude",      :float
    t.column "phone_number",   :string,   :limit => 12
    t.column "yahoo_local_id", :integer
    t.column "vote_count",     :integer,                  :default => 0
  end

  add_index "items", ["keyword_id"], :name => "items_keyword_id_index", :unique => true

  create_table "items_queries", :id => false, :force => true do |t|
    t.column "query_id",   :integer
    t.column "item_id",    :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "keywords", :force => true do |t|
    t.column "value",      :string,   :limit => 16, :null => false
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "keywords", ["value"], :name => "keywords_value_index", :unique => true

  create_table "message_states", :force => true do |t|
    t.column "name", :string, :limit => 48
  end

  create_table "messages", :force => true do |t|
    t.column "to",               :string,   :limit => 48
    t.column "from",             :string,   :limit => 48
    t.column "data",             :string,   :limit => 160
    t.column "carrier_id",       :integer
    t.column "user_id",          :integer
    t.column "created_on",       :datetime
    t.column "updated_on",       :datetime
    t.column "conversation_id",  :integer
    t.column "message_state_id", :integer
  end

  create_table "options", :force => true do |t|
    t.column "object_id",         :integer
    t.column "object_type",       :string,   :limit => 50
    t.column "object_identifier", :string,   :limit => 3
    t.column "step_id",           :integer
    t.column "created_on",        :datetime
    t.column "updated_on",        :datetime
  end

  create_table "queries", :force => true do |t|
    t.column "query_text",    :string,   :limit => 80
    t.column "location_text", :string,   :limit => 80
    t.column "city_id",       :integer
    t.column "state_id",      :integer
    t.column "created_on",    :datetime
    t.column "updated_on",    :datetime
  end

  create_table "segments", :force => true do |t|
    t.column "name",       :string
    t.column "parent_id",  :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "states", :force => true do |t|
    t.column "name",         :string, :limit => 32
    t.column "abbreviation", :string, :limit => 2
  end

  create_table "steps", :force => true do |t|
    t.column "step_id",         :integer
    t.column "type",            :string,   :limit => 50
    t.column "command_id",      :integer
    t.column "created_on",      :datetime
    t.column "updated_on",      :datetime
    t.column "message_id",      :integer
    t.column "keyword_id",      :integer
    t.column "conversation_id", :integer
    t.column "vote_id",         :integer
  end

  add_index "steps", ["command_id"], :name => "steps_command_id_index", :unique => true

  create_table "user_preferences", :force => true do |t|
    t.column "user_id",                :integer,                   :null => false
    t.column "send_vote_confirmation", :boolean, :default => true
  end

  create_table "users", :force => true do |t|
    t.column "phone_number",   :string,   :limit => 28
    t.column "email",          :string,   :limit => 50
    t.column "first_name",     :string,   :limit => 32
    t.column "last_name",      :string,   :limit => 32
    t.column "nick_name",      :string,   :limit => 32
    t.column "street_address", :string,   :limit => 96
    t.column "city_id",        :integer
    t.column "state_id",       :integer
    t.column "zip_code_id",    :integer
    t.column "active",         :boolean,                :default => true
    t.column "created_on",     :datetime
    t.column "updated_on",     :datetime
    t.column "password",       :string,   :limit => 50
    t.column "carrier_id",     :integer
  end

  add_index "users", ["phone_number"], :name => "users_phone_number_index", :unique => true

  create_table "votes", :force => true do |t|
    t.column "user_id",    :integer
    t.column "item_id",    :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  add_index "votes", ["user_id", "item_id"], :name => "votes_user_id_index", :unique => true

  create_table "zip_codes", :force => true do |t|
    t.column "value",    :string,  :limit => 5
    t.column "state_id", :integer
  end

  add_index "zip_codes", ["value"], :name => "zip_codes_value_index", :unique => true

end
